#!/bin/bash

rm -rf output
hadoop fs -rm -r /tmp/gini/output
hadoop fs -mkdir /tmp/gini/output

pig -x mapreduce -p start_year=2010 -p end_year=2019 scripts/avg_period.pig
hadoop fs -rm /tmp/gini/output/avg2010/.pig_schema
hadoop fs -getmerge /tmp/gini/output/avg2010 output/avg2010.csv

pig -x mapreduce -p start_year=2000 -p end_year=2009 scripts/avg_period.pig
hadoop fs -rm /tmp/gini/output/avg2000/.pig_schema
hadoop fs -getmerge /tmp/gini/output/avg2000 output/avg2000.csv

pig -x mapreduce -p start_year=1990 -p end_year=1999 scripts/avg_period.pig
hadoop fs -rm /tmp/gini/output/avg1990/.pig_schema
hadoop fs -getmerge /tmp/gini/output/avg1990 output/avg1990.csv

pig -x mapreduce -p start_year=1980 -p end_year=1989 scripts/avg_period.pig
hadoop fs -rm /tmp/gini/output/avg1980/.pig_schema
hadoop fs -getmerge /tmp/gini/output/avg1980 output/avg1980.csv

pig -x mapreduce -p start_year=1980 -p end_year=1989 -p number=10 scripts/avg_period_limited.pig
hadoop fs -rm /tmp/gini/output/avg1980_limited/.pig_schema
hadoop fs -getmerge /tmp/gini/output/avg1980_limited output/avg1980_limited.csv

pig -x mapreduce scripts/recent.pig
hadoop fs -rm /tmp/gini/output/recent/.pig_schema
hadoop fs -getmerge /tmp/gini/output/recent output/recent.csv

pig -x mapreduce scripts/count_records_by_country.pig
hadoop fs -rm /tmp/gini/output/records_by_country/.pig_schema
hadoop fs -getmerge /tmp/gini/output/records_by_country output/records_by_country.csv

pig -x mapreduce scripts/count_records_by_year.pig
hadoop fs -rm /tmp/gini/output/records_by_year/.pig_schema
hadoop fs -getmerge /tmp/gini/output/records_by_year output/records_by_year.csv