-- REGISTER 'hdfs:///tmp/gini/pigudf.jar';
-- DEFINE TRIM edu.rosehulman.wangc6.Trim();
-- r = load '/tmp/gini/input/raw/gini-index.csv' using PigStorage() as (s:chararray);
-- c = FOREACH r GENERATE TRIM(s) as cs;
-- Store c into '/tmp/gini/input/cleaned/cgini'using PigStorage(',');
REGISTER '${udf_location}';
DEFINE TRIM edu.rosehulman.wangc6.Trim();
r = load '${inputpath}' using PigStorage() as (s:chararray);
c = FOREACH r GENERATE TRIM(s) as cs;
Store c into '${outputpath}'using PigStorage(',');